apiVersion: v1
kind: Service
metadata:
  name: mongo
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    component: mongo
  ports:
  - name: mongo
    port: {{ .Values.mongo.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    component: mongoexpress
  ports:
  - name: http
    port: {{ .Values.mongoexpress.port }}